FROM golang:1.21-alpine AS dev

RUN apk add --no-cache git make gcc musl-dev curl bash

RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest && \
    go install golang.org/x/tools/gopls@latest && \
    go install github.com/cosmtrek/air@latest

WORKDIR /app

COPY go.* ./
RUN go mod download

EXPOSE 8080 2345 6060

CMD ["air"]
